<?php

namespace Database\Seeders;

use App\Models\CvActivity;
use App\Models\CvProfile;
use Illuminate\Database\Seeder;

class CvDataSeeder extends Seeder
{
    public function run(): void
    {
        $profile = CvProfile::current();

        if (CvActivity::count() === 0) {
            $activities = [
                // ══════════════════════════════════════════════════════
                // 1. KEYNOTE SPEAKER & EXPERT TRAINING EXPERIENCE
                // ══════════════════════════════════════════════════════
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'speaker',
                    'title' => 'Narasumber Utama, Kolaborasi Bank Indonesia (KPW BI Sulawesi Tenggara) & Media Indonesia',
                    'organizer' => 'Bank Indonesia (KPW BI Sultra) & Media Indonesia',
                    'category' => 'Keynote / Capacity Building',
                    'year' => '2026',
                    'location' => 'Aveta Hotel Malioboro, Yogyakarta',
                    'flyer_path' => '/images/Insight-Talks-Komdigi.jpeg',
                    'description' => 'Mengisi agenda Capacity Building bertema "AI for Modern Journalism - Meningkatkan Kompetensi Wartawan dalam Pemanfaatan Artificial Intelligence untuk Jurnalisme yang Lebih Berkualitas, Efisien, dan Berdaya Saing" di Aveta Hotel Malioboro, Yogyakarta. Membekali puluhan jurnalis terkait etika AI, otomasi riset berita, verifikasi fakta visual, dan produktivitas ruang redaksi modern.',
                    'order' => 1,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'speaker',
                    'title' => 'Trainer Workshop Insight Talk bersama Kementerian Komdigi dan Media Indonesia',
                    'organizer' => 'Kementerian Komunikasi dan Digital RI (Komdigi) & Media Indonesia',
                    'category' => 'Workshop Jurnalistik & AI',
                    'year' => '2026',
                    'location' => 'Sumatera Selatan',
                    'flyer_path' => '/images/Insight-Talks-Komdigi.jpeg',
                    'description' => 'Menjadi trainer di hadapan rekan-rekan jurnalis dan tim komdigi perwakilan se-Sumatera Selatan, membahas terkait pemanfaatan Tools AI dalam menunjang aktifitas sehari-hari terutama di dunia jurnalis.',
                    'order' => 2,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'speaker',
                    'title' => 'Trainer Utama, Politeknik Akamigas Palembang',
                    'organizer' => 'Politeknik Akamigas Palembang',
                    'category' => 'Lecturer Development Program',
                    'year' => '2026',
                    'location' => 'Kampus Akamigas, Palembang',
                    'flyer_path' => null,
                    'description' => 'Mengisi Lecturer Development Program bertema "Pelatihan Pemanfaatan AI untuk Pembuatan Aplikasi Praktis dan Profesional Tanpa Coding" bagi kalangan akademisi dan dosen teknik.',
                    'order' => 3,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'speaker',
                    'title' => 'Narasumber Ahli, Dinas Pendidikan Kabupaten OKU Timur',
                    'organizer' => 'Dinas Pendidikan Kabupaten OKU Timur',
                    'category' => 'Inovasi Pendidikan & AI',
                    'year' => '2025',
                    'location' => 'OKU Timur, Sumatera Selatan',
                    'flyer_path' => null,
                    'description' => 'Mengisi agenda strategis pemerintah daerah bertema "Inovasi Pembelajaran Berbasis Coding dan AI dalam Kerangka Penguatan Kelembagaan Sekolah bagi Tenaga Pendidik".',
                    'order' => 4,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'speaker',
                    'title' => 'Instruktur Teknologi Akademik, Universitas Sriwijaya (UNSRI)',
                    'organizer' => 'Universitas Sriwijaya (UNSRI)',
                    'category' => 'Pelatihan Tata Kelola Kampus',
                    'year' => '2024',
                    'location' => 'Indralaya / Palembang',
                    'flyer_path' => null,
                    'description' => 'Mengedukasi jajaran dosen dan tenaga kependidikan kampus melalui pelatihan manajerial tata kelola digital bertajuk "Managing and Documenting Files for Enhancing Work Effectiveness".',
                    'order' => 5,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'speaker',
                    'title' => 'Pemateri Nasional Kolaborasi IGI Kabupaten Ogan Ilir',
                    'organizer' => 'Ikatan Guru Indonesia (IGI) Kabupaten Ogan Ilir',
                    'category' => 'Pelatihan Daring Nasional',
                    'year' => '2022',
                    'location' => 'Daring Nasional (2.200+ Pendidik)',
                    'flyer_path' => null,
                    'description' => 'Merancang dan memimpin pelatihan daring berskala masif untuk lebih dari 2.200 guru se-Indonesia dalam program "Satu Guru Satu Aplikasi Android", mendorong kemandirian pendidik menciptakan media pembelajaran interaktif.',
                    'order' => 6,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],

                // ══════════════════════════════════════════════════════
                // 2. SOFTWARE ENGINEERING & RELEVANT PROJECTS
                // ══════════════════════════════════════════════════════
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'SmartVerse.id - 5 Flagship SaaS Ecosystem',
                    'organizer' => 'SmartVerseID & CV. Beranda Teknologi Digital',
                    'category' => 'Proprietary SaaS Ecosystem',
                    'year' => '2024 - 2026',
                    'location' => 'Palembang & Nasional',
                    'url' => 'https://smartverse.id',
                    'flyer_path' => '/images/smartverse/logo-smartverse.webp',
                    'description' => 'Menaungi 5 lini produk SaaS unggulan: SmartEdu (ERP Sekolah & RAG AI), SmartSDM (Mobile HRIS Biometrik Liveness & Anti-Mock GPS), SmartSynth (Lab Forensik Konten AI & C2PA), SmartNews (CMS Media Standar Dewan Pers), dan SmartFeed (Studio Visual AI Marketing). Berbasis Laravel 13, PHP 8.4, dan React Native.',
                    'order' => 1,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'SmartEdu SIT Robbani (Enterprise School ERP)',
                    'organizer' => 'SIT Robbani Ogan Ilir',
                    'category' => 'EdTech & School Management',
                    'year' => '2023 - 2026',
                    'location' => 'Ogan Ilir, Sumatera Selatan',
                    'url' => 'https://sitrobbani.sch.id',
                    'flyer_path' => '/images/smartverse/SmartEDU.webp',
                    'description' => 'Merancang arsitektur sistem informasi enterprise terpadu untuk SIT Robbani Ogan Ilir (23+ modul, SPMB Online 5-step smart wizard ber-auto-save, generator PDF 4-halaman siap cetak, e-SPP billing, raport digital JSIT, dan chatbot RAG AI cerdas).',
                    'order' => 2,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Pondok Pesantren Raudhatul Ulum Sakatiga',
                    'organizer' => 'Ponpes Raudhatul Ulum Sakatiga',
                    'category' => 'EdTech & Portal Pesantren',
                    'year' => '2024 - 2026',
                    'location' => 'Ogan Ilir, Sumatera Selatan',
                    'url' => 'https://ppru.ac.id',
                    'flyer_path' => null,
                    'description' => 'Mengembangkan website resmi & portal informasi Ponpes Raudhatul Ulum Sakatiga (Laravel 13, Tailwind CSS v4, dynamic CMS beranda, portal PSB online, infaq/wakaf pembangunan, dan otomasi pengujian sistem dengan 58 Pest test suites).',
                    'order' => 3,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Hinewai Skin & Beauty (Australia)',
                    'organizer' => 'Hinewai Australia',
                    'category' => 'Global & International Projects',
                    'year' => '2023 - 2024',
                    'location' => 'Australia',
                    'url' => null,
                    'flyer_path' => null,
                    'description' => 'Merancang dan mengembangkan platform e-commerce premium untuk operasional penjualan produk kosmetik dan perawatan kulit di pasar Australia.',
                    'order' => 4,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Buffalo Horn and E-Course (Australia)',
                    'organizer' => 'Buffalo Horn Australia',
                    'category' => 'Global & International Projects',
                    'year' => '2023 - 2024',
                    'location' => 'Australia',
                    'url' => null,
                    'flyer_path' => null,
                    'description' => 'Mengembangkan platform e-commerce terintegrasi sekaligus sistem e-learning (kursus daring) untuk operasional komersial di Australia.',
                    'order' => 5,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Master Your Muscles (Malaysia)',
                    'organizer' => 'Master Your Muscles Kuala Lumpur',
                    'category' => 'Global & International Projects',
                    'year' => '2024',
                    'location' => 'Kuala Lumpur, Malaysia',
                    'url' => null,
                    'flyer_path' => null,
                    'description' => 'Mengembangkan platform e-commerce dan sistem pemesanan pelatihan bagi jaringan praktisi kesehatan internasional.',
                    'order' => 6,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'NZBodyTalk Alliance (Selandia Baru)',
                    'organizer' => 'NZBodyTalk Alliance New Zealand',
                    'category' => 'Global & International Projects',
                    'year' => '2023',
                    'location' => 'Selandia Baru (New Zealand)',
                    'url' => null,
                    'flyer_path' => null,
                    'description' => 'Membangun sistem pendaftaran dan portal keanggotaan terintegrasi untuk aliansi komunitas praktisi BodyTalk di Selandia Baru.',
                    'order' => 7,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Akselerasi Kesehatan Ibu & Anak (Magenta & Sekanak)',
                    'organizer' => 'Tim Riset & Inovasi Kesehatan',
                    'category' => 'Health, Medical & Nutrition Tech',
                    'year' => '2023 - 2025',
                    'location' => 'Palembang & Nasional',
                    'url' => 'https://magenta.aplikasikesehatan.com',
                    'flyer_path' => null,
                    'description' => 'Mengembangkan aplikasi Magenta (Monitoring Status Gizi & Edukasi Anak Balita dengan kalkulasi skor WHO-Z berbasis cloud) dan Sekanak (Aplikasi Pemantauan gizi, riwayat imunisasi, dan morbiditas balita di sekanak.aplikasikesehatan.com).',
                    'order' => 8,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Riset & Sistem Informasi Kesehatan (Kolaborasi FKM UNSRI)',
                    'organizer' => 'Fakultas Kesehatan Masyarakat UNSRI',
                    'category' => 'Health, Medical & Nutrition Tech',
                    'year' => '2022 - 2024',
                    'location' => 'Palembang',
                    'url' => null,
                    'flyer_path' => null,
                    'description' => 'Merancang aplikasi DERI PTM untuk deteksi dini risiko Penyakit Tidak Menular, platform Lapor Vaksin Covid-19, serta Zikari (aplikasi pemantauan asupan gizi mahasiswa).',
                    'order' => 9,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => "Aplikasi Penilaian Bulutangkis Unsri — SA'BAWA",
                    'organizer' => 'Dosen Penjas FKIP Universitas Sriwijaya',
                    'category' => 'EdTech & Gamifikasi Olahraga',
                    'year' => '2024',
                    'location' => 'Indralaya, Ogan Ilir',
                    'url' => 'https://sa-badmintonapp.com',
                    'flyer_path' => null,
                    'description' => 'Membangun "SA\'BAWA - Badminton Assessment WebApp" untuk digitalisasi pengolahan nilai ilmiah 4 teknik bulutangkis berbasis Laravel 13, Tailwind CSS, Alpine.js, kalkulasi norma otomatis, dan offline-first local storage persistence.',
                    'order' => 10,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Portal Profil & Akademik SMPS & SMA IT Ishlahul Ummah Prabumulih',
                    'organizer' => 'Yayasan Ishlahul Ummah Prabumulih',
                    'category' => 'EdTech & School Management',
                    'year' => '2024',
                    'location' => 'Prabumulih, Sumatera Selatan',
                    'url' => 'https://smpitishumpbm.sch.id',
                    'flyer_path' => null,
                    'description' => 'Membangun portal profil dan sistem informasi akademik SMP IT & SMA IT Ishum berstandar JSIT Indonesia (Laravel 13, Tailwind CSS v4, modul SPMB online, manajemen GTK, dan modul ajar siswa).',
                    'order' => 11,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Sistem Informasi & Website PWI Kabupaten Banyuasin',
                    'organizer' => 'Persatuan Wartawan Indonesia (PWI) Banyuasin',
                    'category' => 'Institutional & Association',
                    'year' => '2024',
                    'location' => 'Banyuasin, Sumatera Selatan',
                    'url' => 'https://pwiba.or.id',
                    'flyer_path' => null,
                    'description' => 'Membangun portal informasi dan sistem manajemen administrasi PWI Banyuasin: pemetaan wartawan berdasar tingkatan UKW (Muda, Madya, Utama), direktori media mitra, serta generator surat dinas otomatis (Surat Tugas, Audiensi) ber-KOP resmi.',
                    'order' => 12,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Sistem Informasi Keanggotaan DPD APPSI Banyuasin',
                    'organizer' => 'DPD APPSI Kab. Banyuasin',
                    'category' => 'Institutional & Association',
                    'year' => '2024',
                    'location' => 'Banyuasin, Sumatera Selatan',
                    'url' => 'https://appsiba.or.id',
                    'flyer_path' => null,
                    'description' => 'Mengembangkan portal resmi & pendaftaran keanggotaan Asosiasi Pedagang Pasar Seluruh Indonesia: direktori pedagang pasar tradisional multi-komoditas, registrasi online 1-click approval NPA, cetak KTA digital ber-QR, serta manajemen surat dinas TTE verifikasi QR.',
                    'order' => 13,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Digitalisasi Pariwisata & Budaya Lubuk Linggau',
                    'organizer' => 'Komunitas Budaya Jelajah Sejarah',
                    'category' => 'Cultural Preservation & Tourism',
                    'year' => '2023 - 2024',
                    'location' => 'Lubuk Linggau, Sumatera Selatan',
                    'url' => 'https://karitcaunpari.com',
                    'flyer_path' => null,
                    'description' => 'Membangun ekosistem digital untuk pelestarian sejarah lokal melalui platform Jelajah Sejarah Batu Urip (karitcaunpari.com) dan komunitas KAMSEDA SEYU (kamsedaseyu.com).',
                    'order' => 14,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'Sistem Manajemen Ziswaf & Kerelawanan (Dompet Sosial Robbani)',
                    'organizer' => 'Dompet Sosial Robbani (DSRP)',
                    'category' => 'Social Enterprise & ZISWAF',
                    'year' => '2023 - 2025',
                    'location' => 'Ogan Ilir, Sumatera Selatan',
                    'url' => 'https://dsrp.or.id',
                    'flyer_path' => null,
                    'description' => 'Mengembangkan aplikasi operasional dan basis data relawan untuk lembaga Zakat, Infaq, Sadaqah, dan Waqf pada Dompet Sosial Robbani (dsrp.or.id).',
                    'order' => 15,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
                [
                    'cv_profile_id' => $profile->id,
                    'type' => 'project',
                    'title' => 'E-Kantin Assalaam Papua & Robbani Mart / Kursus',
                    'organizer' => 'Assalaam Papua & Koperasi Robbani',
                    'category' => 'POS Cashless & E-Commerce',
                    'year' => '2023 - 2024',
                    'location' => 'Jayapura, Papua & Ogan Ilir',
                    'url' => 'https://assalaampapua.com/kantin',
                    'flyer_path' => null,
                    'description' => 'Merancang sistem kasir digital (POS) dan dompet santri non-tunai (cashless canteen) untuk ekosistem pesantren/sekolah Assalaam di Papua, platform e-commerce warung Robbani Mart, dan pendaftaran kursus robbanikursus.com.',
                    'order' => 16,
                    'is_featured' => true,
                    'show_in_print' => true,
                ],
            ];

            foreach ($activities as $item) {
                CvActivity::create($item);
            }
        }
    }
}
