---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pesonaas/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
